name: Workflow01
on: push

jobs:
  my-job:
    name: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - name: FlaskTest
      run: |
        pytest