name: Workflow01
on: push

jobs:
  my-job:
    name: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - name: FlaskTest
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt
        python3 server.py > log.txt 2>&1 &
        pytest